apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: datagrids.datagrid.redhat.com
spec:
  group: datagrid.redhat.com
  names:
    kind: DataGrid
    listKind: DataGridList
    plural: datagrids
    singular: datagrid
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
