apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeready-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: codeready-operator
  template:
    metadata:
      labels:
        name: codeready-operator
    spec:
      serviceAccountName: codeready-operator
      containers:
        - name: codeready-operator
          # Replace this with the built image name
          image: "docker.io/schtool/codeready-operator:0.1"
          imagePullPolicy: "Always"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "codeready-operator"
