apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  creationTimestamp: null
  name: codeready-operator.v0.1.0
  namespace: placeholder
  annotations:
    tectonic-visibility: ocs
    capabilities: Full Lifecycle
    categories: "Other"
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: CodeReady
      name: codereadys.codeready.redhat.com
      version: v1alpha1
      displayName: "Red Hat CodeReady Workspaces"
      description: "Browser-based Developer IDE for OpenShift"
  description: |
    Red Hat CodeReady Workspaces - A collaborative kubernetes-native development solution that delivers OpenShift workspaces and in-browser IDE for rapid cloud application development.
    ----
    * Built on the open Eclipse Che project, Red Hat CodeReady Workspaces provides developer workspaces, which include all the tools and the dependencies that are needed to code, build, test, run, and debug applications. The entire product runs in an OpenShift cluster hosted on-premises or in the cloud and eliminates the need to install anything on a local machine.
    * Centralized developer environments
    * Container-based workspaces
    * Source code protection
    * Pre-built or custom stacks
    * Enterprise integration
    * [More Info](https://developers.redhat.com/products/codeready-workspaces/overview/)

  displayName: Red Hat CodeReady Workspaces
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAOEAAACpCAYAAADduFp7AAAMSmlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnltSSWiBUKSE3kQp0qWE0CIISBVshCSQUGJMCCJ2FlkF1y4ioK7oqoiLrgWQtaKudVHs/aGIysq6WLCh8iYF1tXvvfe9831z758z5/ynZO69MwDo1PKk0jxUF4B8SYEsITKUNTEtnUXqAgjAgBGwBJ48vlzKjo+PAVCG7v+UN9ehNZQrrkqub+f/q+gJhHI+AEg8xJkCOT8f4v0A4KV8qawAAKIv1NvMLJAq8WSIDWQwQYilSpytxqVKnKnGVSqbpAQOxLsAINN4PFk2ANotUM8q5GdDHu2bELtJBGIJADpkiIP4Ip4A4iiIR+bnT1diaAccM7/gyf4HZ+YwJ4+XPYzVtaiEHCaWS/N4s/7Pdvxvyc9TDMWwh4MmkkUlKGuGfbuZOz1aiWkQ90oyY+Mg1of4nVigsocYpYoUUclqe9SML+fAngEmxG4CXlg0xGYQR0jyYmM0+swscQQXYrhC0CJxATdJ47tYKA9P1HDWyqYnxA3hLBmHrfFt5MlUcZX2JxW5yWwN/02RkDvE/7pYlJSqzhmjFopTYiHWhpgpz02MVttgtsUiTuyQjUyRoMzfFmJ/oSQyVM2PTc2SRSRo7GX58qF6scUiMTdWg6sLRElRGp5dfJ4qf2OIW4QSdvIQj1A+MWaoFoEwLFxdO3ZJKEnW1It1SgtCEzS+L6V58Rp7nCrMi1TqrSE2kxcmanzxoAK4INX8eKy0ID5JnSeemcMbF6/OBy8CMYADwgALKODIBNNBDhC39zb3wl/qmQjAAzKQDYTAVaMZ8khVzUjgNREUgz8hEgL5sF+oalYICqH+07BWfXUFWarZQpVHLngMcT6IBnnwt0LlJRmOlgIeQY34m+h8mGseHMq5b3VsqInRaBRDvCydIUtiODGMGEWMIDrhpngQHoDHwGsIHB64L+43lO3f9oTHhA7CQ8I1Qifh1jRxieyrelhgPOiEESI0NWd+WTNuD1m98FA8EPJDbpyJmwJXfAyMxMaDYWwvqOVoMldW/zX3P2r4ousaO4obBaUYUUIojl97ajtrew2zKHv6ZYfUuWYO95UzPPN1fM4XnRbAe/TXlthibB92GjuOncUOYc2AhR3FWrAL2GElHl5Fj1SraChagiqfXMgj/iYeTxNT2Um5W4Nbj9tH9VyBsEj5fgSc6dJZMnG2qIDFhm9+IYsr4Y8ayfJwc/cDQPkdUb+mXjFV3weEee5vXclrAAIFg4ODh/7WxcBnev8iAKiP/9Y5HIGvAyMAzlTwFbJCtQ5XXgiACnTgE2UCLIANcIT1eABvEABCQDgYB+JAEkgDU2GXRXA9y8BMMAcsBGWgAqwAa0E12AS2gB3gZ7AXNIND4Dj4DZwHl8A1cAeunm7wDPSBN2AAQRASQkcYiAliidghLogH4osEIeFIDJKApCEZSDYiQRTIHOQ7pAJZhVQjm5F65BfkIHIcOYt0ILeQB0gP8hL5gGIoDTVAzVF7dDTqi7LRaDQJnYJmozPQYrQUXYZWoXXoLrQJPY6eR6+hnegztB8DmBbGxKwwV8wX42BxWDqWhcmweVg5VonVYY1YK/yfr2CdWC/2HifiDJyFu8IVHIUn43x8Bj4PX4pX4zvwJvwkfgV/gPfhnwl0ghnBheBP4BImErIJMwllhErCNsIBwin4NHUT3hCJRCbRgegDn8Y0Yg5xNnEpcQNxN/EYsYPYRewnkUgmJBdSICmOxCMVkMpI60m7SEdJl0ndpHdkLbIl2YMcQU4nS8gl5EryTvIR8mXyE/IARZdiR/GnxFEElFmU5ZStlFbKRUo3ZYCqR3WgBlKTqDnUhdQqaiP1FPUu9ZWWlpa1lp/WBC2x1gKtKq09Wme0Hmi9p+nTnGkc2mSagraMtp12jHaL9opOp9vTQ+jp9AL6Mno9/QT9Pv2dNkN7lDZXW6A9X7tGu0n7svZzHYqOnQ5bZ6pOsU6lzj6dizq9uhRde12OLk93nm6N7kHdG7r9egw9d704vXy9pXo79c7qPdUn6dvrh+sL9Ev1t+if0O9iYAwbBofBZ3zH2Mo4xeg2IBo4GHANcgwqDH42aDfoM9Q3HGOYYlhkWGN42LCTiTHtmVxmHnM5cy/zOvODkbkR20hotMSo0eiy0VvjEcYhxkLjcuPdxteMP5iwTMJNck1WmjSb3DPFTZ1NJ5jONN1oesq0d4TBiIAR/BHlI/aOuG2GmjmbJZjNNttidsGs39zCPNJcar7e/IR5rwXTIsQix2KNxRGLHkuGZZCl2HKN5VHLP1iGLDYrj1XFOsnqszKzirJSWG22arcasHawTrYusd5tfc+GauNrk2WzxqbNps/W0na87RzbBtvbdhQ7XzuR3Tq703Zv7R3sU+2/t2+2f+pg7MB1KHZocLjrSHcMdpzhWOd41Yno5OuU67TB6ZIz6uzlLHKucb7ogrp4u4hdNrh0jCSM9BspGVk38oYrzZXtWuja4PpgFHNUzKiSUc2jno+2HZ0+euXo06M/u3m55bltdbvjru8+zr3EvdX9pYezB9+jxuOqJ90zwnO+Z4vnizEuY4RjNo656cXwGu/1vVeb1ydvH2+Zd6N3j4+tT4ZPrc8NXwPfeN+lvmf8CH6hfvP9Dvm99/f2L/Df6/9XgGtAbsDOgKdjHcYKx24d2xVoHcgL3BzYGcQKygj6Magz2CqYF1wX/DDEJkQQsi3kCduJncPexX4e6hYqCz0Q+pbjz5nLORaGhUWGlYe1h+uHJ4dXh9+PsI7IjmiI6Iv0ipwdeSyKEBUdtTLqBtecy+fWc/vG+YybO+5kNC06Mbo6+mGMc4wspnU8On7c+NXj78baxUpim+NAHDduddy9eIf4GfG/TiBOiJ9QM+FxgnvCnITTiYzEaYk7E98khSYtT7qT7JisSG5L0UmZnFKf8jY1LHVVaufE0RPnTjyfZpomTmtJJ6WnpG9L758UPmntpO7JXpPLJl+f4jClaMrZqaZT86YenqYzjTdtXwYhIzVjZ8ZHXhyvjtefyc2szezjc/jr+M8EIYI1gh5hoHCV8ElWYNaqrKfZgdmrs3tEwaJKUa+YI64Wv8iJytmU8zY3Lnd77mBeat7ufHJ+Rv5Bib4kV3JyusX0oukdUhdpmbRzhv+MtTP6ZNGybXJEPkXeUmAAN+wXFI6KRYoHhUGFNYXvZqbM3FekVyQpujDLedaSWU+KI4p/mo3P5s9um2M1Z+GcB3PZczfPQ+ZlzmubbzO/dH73gsgFOxZSF+Yu/L3ErWRVyevvUr9rLTUvXVDatShyUUOZdpms7Mb3Ad9vWowvFi9uX+K5ZP2Sz+WC8nMVbhWVFR+X8pee+8H9h6ofBpdlLWtf7r184wriCsmK6yuDV+5YpbeqeFXX6vGrm9aw1pSveb122tqzlWMqN62jrlOs66yKqWpZb7t+xfqP1aLqazWhNbtrzWqX1L7dINhweWPIxsZN5psqNn34Ufzjzc2Rm5vq7OsqtxC3FG55vDVl6+mffH+q32a6rWLbp+2S7Z07EnacrPepr99ptnN5A9qgaOjZNXnXpZ/Dfm5pdG3cvJu5u2IP2KPY88cvGb9c3xu9t22f777G/Xb7aw8wDpQ3IU2zmvqaRc2dLWktHQfHHWxrDWg98OuoX7cfsjpUc9jw8PIj1COlRwaPFh/tPyY91ns8+3hX27S2Oycmnrh6csLJ9lPRp878FvHbidPs00fPBJ45dNb/7MFzvueaz3ufb7rgdeHA716/H2j3bm+66HOx5ZLfpdaOsR1HLgdfPn4l7MpvV7lXz1+LvdZxPfn6zRuTb3TeFNx8eivv1ovbhbcH7iy4S7hbfk/3XuV9s/t1/3L61+5O787DD8IeXHiY+PBOF7/r2SP5o4/dpY/pjyufWD6pf+rx9FBPRM+lPyb90f1M+mygt+xPvT9rnzs+3/9XyF8X+ib2db+QvRh8ufSVyavtr8e8buuP77//Jv/NwNvydybvdrz3fX/6Q+qHJwMzP5I+Vn1y+tT6Ofrz3cH8wUEpT8ZTbQUwONCsLABebgeAngYA4xLcP0xSn/NUgqjPpioE/hNWnwVV4g1AI7wpt+ucYwDsgcN+AeQOAUC5VU8KAain5/DQiDzL00PNRYMnHsK7wcFX5gCQWgH4JBscHNgwOPhpK0z2FgDHZqjPl0ohwrPBjyFKdM1YsAB8Jf8GIFx/iuJY1vMAAAAJcEhZcwAAFiUAABYlAUlSJPAAAAIEaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA1LjQuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDxleGlmOlBpeGVsWURpbWVuc2lvbj40MzA8L2V4aWY6UGl4ZWxZRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFhEaW1lbnNpb24+NTc0PC9leGlmOlBpeGVsWERpbWVuc2lvbj4KICAgICAgICAgPHRpZmY6T3JpZW50YXRpb24+MTwvdGlmZjpPcmllbnRhdGlvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cgi1g14AABLsSURBVHgB7Z1NjBxJVsdfZH109Yfd7bG94zY9u6vZwcvOIAEy4rKAzLLiAhIrDSuEuKzEhROXvXCzfNnLnpAQQlpASEjM8jEgtCAQoN1hBEIgAYNYdmH5mNHYgz1je/zRbru7KjOC/8uqbGeXq7qzO6OyMrL+oS5nZkTkixe/eC8i6iOfRZhIgARIgARIgARIgARIgARIgARIgARIgARIgARIgARIgARIoHICpsoW33z9dffHr74q53/sRyXeeYSmXfnmIaK1vCL33/w7+enfe01++Gd/rlSfnHPmb//odfuHr/6MXPiJH5fB3dtooO1H1/K9PVSCESOxtfK9uw/lwrnzEptIjAOgExLR0TnhrVP1nIXMqY3lCxRDb1n6f/EN+dhv/6Zc+sIv+O5avrVjnat1VZbiOJY7aK379v9I/M573tptbT6Xyk0SW1qmMcZ9/atfTeWtXH9X9r79X94NsbSShwiIUTa40JP+nbdlEDsxtTG1Q5Suokid8OwL0kdbSX9QRYuF26jUCU1kZAmqddY3xHzXHhZCnRdLJLUwm0jrzDlZuvkhDM6PxUWZnmunxJ5bEbO0Ul7XEt08zq0GSKPVJYm6HYnAV1dHJiUAFmvrEsl1MVFUKySVOqHuPnWtckkirg8nTLejZRxx6IQqb7gGlpH1dFwgZQfyVh22dm73MaZQHTQ/sp+24vts6GzYToNvCy/It9DZ08TkW9vK5emEDzvRVLeRrNYJAWB/XtaTlMZ+jvI5Zipz7/SmIHUbpatpDW1CDbluIzdd/ZHa0Fl1ZxoSyLHIndaCTr3W5VogUSWcOiFTQwnUbT6lE042NP3olqmhBLgSBjGwEZ0wiHFqhpJcCSeMIz7a2JmQzSwSmAkBOuEErPhYnyvhBC5NyeJ7wgBGEh/z7wagJlU8DoGc5/E94XHAzatuJMFvR3M2Ny+KtW23bmy4HZ1gKlgJg3fCus32EzBXm5UDkjutVocprVXqhDDu8j/unNIRn9n4+Rt+JhN2qttsP3eaOSC507mrpQpU6oQw7nr9cnbKEBgrT6YUBZNdt9l+7uByQHKnc1dLFajUCdGe/si/9skafjBT+0FqkIKVOiFmIP3Vdu2TcSYIPQ8DWbct12G6VlKWA5I7raTpoxqp1AmhTBgfeBjLryiOspyAyxd6O4oZKIwPPIwJ3gnrZmhz99kaA6l6JXw498EoooBzwW9Hi3STdepBoNLnCTEZ3d/fj+tDlvoqk9LZTWWUlDOmg3XR0AlTHVW8B13H2pjZ5UhX/P51qHeNV4CZMXhGMCCMTEQPo9Nnas0ro1IndFH0oTYYLfUkOnXGT5/x1WPUW5GWSvP0FHk7ivZUXrSEMBFnnhfT6frRdcZS1N8snND0OmIQ3kKDPNEHAUUhwPOM2p1eerITiPKSKnVCa+Nb+mZrcP+exP973UsHVIh9IUkD+DgN5+Ah2ThOg28MtrdlcP39oAxZvwOyWxtiTR/RHAYSpaE5joKi3MbdNc9yvGxc3qT7tU4mY9L94/eMX4+3UfIak7VJtkQDXGjYkjqlSp0QQ/FuD73vLGGWfg5rzfgPaNIwEtnATcKkg5mV49zA1hL7MOp1t7FW4ckH5+U9J2bLfhqQqtMWpyeryNFtXpZSNUa65FXKymd1PKQtLdJYOCZOxNy4L63v/ojYqI3VsIjBTROcSoXgXN+P3bdpsscFFa03fl+R66Fs0+ulO6aaLYTPTH9FenTiOvjZWnTz5s1ep9NpPXr0qHVGw5qN0gMcrbXudBzbZH0di1FsN/f27H/HsXvpwQP7xva2u3Llir127ZpcvXrVYUtRxjKyZiceoaeRa9f2dcsqXctOxo6qz1hW2JdTrBRAmtXPsEeJ2pMACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACZAACRQl8MzT40VvrFs9fRp++9/+xt7761+T1vpHxcV9jegDNQs8DJ5VKUpD6xepe1S9Ubum1ZHk0Qey+spn5OxnvxCViRqgHO6+8Zrdeetr0jq9BQ4IHDfO4TC98mX587TDyEC0jM7FrkQrONHIGUU41M1YZqIP2Jiu2L0PpLf1Wdn4vp8vTKbSGDMz6ftIqBruvb//E9n919+X9sUL4ga3ZtmcV9mmc0aS2/eku3lJI4Gp6Z846f23Xv8yOLwGDnDC/o0Ty5p4o2rXfkWitX9HiKAOLmL4oTkw1an1abW8FWbX+SOqpHU0T9P4ffm6+bIsf3jX07ay/OyYlWfHfL6ea8rrOMx5Vp7m5+/N6mXHYUw7xPZpXZJk5zvS2XglKyp0bIwTam9NuyutcwhVePoybGNbcwpBmG8lDG97FQb95wixuOpFFZUz5PD9CG33okcO0NW1JVo+jTCTF6GzBhAcmuc46WnXQ3dVt32ajjrPysePmYRxmVm9rDw75vPz51l5dszKsqPm58+zetlxWIZobhHGzyI6X2clKyp0bJQTWmd3XF9WJd7BSngf5NRI5pgOmz731cI8qpHcsHt2MRT3kJxNPHPIOqJbUMS1SxCFzmKSS8D3MOv00JdgRCCqnVJyCUKWWQ2sWDw1yglhErr8YTqCZaTvg+ZsIYWaz3SF5sao/j7SNhB45JB1JNNVr/WVrYQ+VA5cBuxtf33PcBXs0pyXioJaFq/mZSUp3pznmsbT/1rlS86R3dO5nykjcFIaDXNChwDAQSc/+jsNhMxUNYFjLoD76jXKCfHuKnTj86W/Lzn7hsKT2RFolBMiCHzQxoevF/zob7gSzs5l/EtulBPi86mw3xM6T/o7T+8t/dsbJU4g0CgnxCd2Tyb0MaAsT/obT3ICIheyqo1yQic2jP+Oe4rF4D/29KO/9SRnip7M9kugUU7o7T2VX8aFpeF7Jr4nLEyrORWb5YTWBb0dxUruRX98SuxFTnPMvJqe8HtCcDYm0v8IONhknPGiP34G50VOsCDnpDi/JwR4zERhrwDG00puAucwJyeaV7ON2o5aI0GvANZwJZyXI8yz3UY5YWTD3oYZT/rbKOxt+TwdYh5tN8oJ8Txr0CuhiTythJ6ceR4GuYhtNsoJ8akgnsoLN+FpPS/646saL3KOJnnSjyKOlrxINZrlhEYQUCXchMAWXvS3kniRczTJk34of7TkEGuclEazHurdN+I8jvx5XYd2qGMkzovzRK49kpPve/78JByyVU/l5GXpeVZ2ErnNueekFBrlhAg01pcWBjVCCAazrF8chjHCZil9SB1RSrxsI62x/TSyh8o1Pbx8bXjgcBrcKYJc3Tmr3HJxqcIYnyJaaogSAzapyR2Pd6OcEJ9H9J2G+Fj9J9jI3RGQIgTnW8chQJWGbLG7O36cMN7p24fwldV/wdr6vl8OeOPq9l4Q6V5HjBlwC2Sem/kI64bAfgKxjTTOzPEe5mkUQnf79qkn2+99Sjoaii+8tNxrfduc/57ScWbc7f8Ah92UA+KQqnmM0vC849r7eQNRq8nqtPXMScc5/KFO2w36A9ELRFlz2F/gaJ10UdjpolzztZ4e9XoXZx3bW8JPdvA5dW+pa3dx4pZwj1i37HruMeqv4Fx/qY5Ttwp5j1AiePpqbaVnt/XXs9a6U6dwj1tDPmZVl7j7iNvl1hN3xq3j132Ju4Nq55B/G8fzNnby/Hl38+b/yebm805uYILY2nTyjuDvHfl4vAU5SC/13be+JfLyyy/jGhM1/uTyZZy/kf7JlSvDevIHon/y+c+PrnEu19I/uXo1l6f5o5TGmDmwT89KeCQBEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEiABEpg3gQNP1v/WN37V/e43vyRbKz8gA4tYQRqjRZ8jPlBrpPLE/LFMPHCN/x9COohJ8s2HX5Nf/6l/lMsv/dAkacfi8DtvfsV95a1flJfWflL2EjyjvR9LZrz9vO5jZfstIl+LtJPH1iy9MdfIWBvZ5eiIuKjypB/Jpz95SjY/8qHEGh6CqTICkenKIHlfNno/KJ/71G8ce7RnpejBGDMO/4nB4I4M4lj6dgCbLK8nYmAi2ElLHsfoQmazZXsDOU8GCfTEK1HBAaQ0/IGFzi2EdYgktjFeJ/D7GXc1mze0mfz5pGaPKj/sHr1XU3kLe6rnUfpYLAgDu4vgGsO26/LvASdUh+m1Lki71cUAIPbX/gpTRl2DlbArKxqYywtyyAHM5daatKMOtETkkyASem8QETRpSWT0tYQXdgo11v0oo66x6mOqKWXdlXXBfAVHDclXn3TACVWtBKEvnUtg3HBCrIxlkzqedTA+jCgi95QVN7rfQd6jdKJQ2aEkoxqPOKAH4AzNyyOeafd9jdhMlSwsXG1F3wPUq1fHC5BYuLPPVqxXt5/VjzkLQCAzwuxYky5X5oQ16S/VWGQC2a4jO9aEBZ2wJgNBNSogULMVMOsxnTAjwWPzCWQrYM2ckU7YfNNjD8cJZM44nj+nazrhnMCz2TkS4Eo4R/hsmgSUAFdC2gEJkECeALejeRo8bzaBbBuaHWvSWzphTQaCaiwuATrh4o794vac7wkXd+zZ8zkTqJnzZTS4EmYkeGw+gey9YHasSY/phDUZCKqxuATohIs79ovX82w7mh1rQoBOWJOBoBoVEuB2tELYbIoEJhGo2Up44Ml6fQq+jcf/I9OWlklw5UNbA1kt6WLN9RMuQ391pHqehZ4tyD7QhUnIa5OngZ5aUQTt9dUGj9r9gqo2rGahCCwR3DsQXa8N4AELThDW4mH8tuzGLyLQ0y4ULu+E6ngWcu8MEFQgjedQHq/q+SC+K3vxY9lNdsoLrEiCxph5gkBPiV1GeI5tHHViqqjxmjSjO0HfXc5kZsdpXTVuSWJ3B/bYn1ZlLvkHnLDdasvFlcuysfwcolJptDUfaRjo6cXBpkRYBXwk1XNr5RVZXz4jvWTZk54+NDtMBqY0rITLbSPd9oostc5jLUTyA/lAwzp5ajyf7JgVDq/16tk3Rc/WHdbK8lXN/F2aH1rS3UfLagjO5dBUp74kQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkEDCBSmMU/Ok/3HBffOM9ubzelT2LYAn5eAmlIaqwLAjDpG5ljU0qm964holYa0fy9Xt9+ZUf2ZRXP/3R4wmYIPov37rlfvmv3pVLa22EEZlQYWpW1scJFaCVKpYgcM3S1mlZf25ZXIL6pbWd0NaMsroIuPP2XiJf/OSGfObjGwFpXg7IgRgz5UQdffdeP5b/fH9XNmAoD9RAAkgx1NxEqLgbt3Zldy/2orE6yj/fRiCtfkceYTLyaW3qeBfPJnLvcSw2tt4i3Hnp+BFClhGC6M+eJPJLgdjGEd0pXFypE7YimNtyS84stRCgSdeY+iddqNY70HulJe2WH3dJQz/2WnJ2KZLVY62ER/NycOo1BJNaxuqdivaj8tENe6jRg3283HYIZelBWEAiKnXCNOIhnG8AQ9HtaBBOCCUHGiQOekNlTwmCIE8Z7Pl2QuUL8W3ItinwMCxatdRdx0Po7Ckypqexmr2YSp0w3XflbCJ3OvuelmjBV9DiAyqg8xo2UIMTek2pXEjMjl6Fz16Yn6CYs9fTZwvV9tmzvfkEcbisYBU/vFs1LF1E0tU6YQ0HvZhKoazZxXrDWvUiUK0TBmvLizg/18tQm6xNtU5IW67UlsLDHZ7GPga0Wif0oTFlFCYQ3sYjPI0LD8YhFat1wsVkfAh+Fo0TWEQTqdYJx4kHc72IpjGfwVnEDWm1Thgs4TAVD1Pr+Tj/PFut1gnn2VO2TQI1JUAnLDQwYW5Hw9S60IA0qlK1TkiraJTxsDN+CFTrhH50phQSaBQBOmGjhpOdCZEAnTDEUaPOjSJAJ2zUcIbfmUX82KBaJ9QvrgL88mqWjx/7xpF/INa37CpcPESdy3Kp/qFeuL2GL/AUKaJs/wvd30qfkNUHcD2mEQPl4FOustWZNUqletbZY/cniVK9u3gh3tNCpWqdUKe50Ss/Y9eZuOqZroS+FVa5o5fP/o/wpjoPV/BwLFp1TxSGnixQqtQJYw3SgqAqNxHn7wPEQjnAWi8m2ct4/nGvdTDzDU1rIxv0XLmePsG9lwzm6L1hbJysWpkjgqClHN4Dh7vgoKtXXsUDF6rEeJ+nNK5VB5D3CTRwGm1Y5a2ZgaRVqPsO9NdYM0wkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIkQAIk0EQC/w+dXxwZPINg0gAAAABJRU5ErkJggg==
    mediatype: image/png
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: true
  - type: AllNamespaces
    supported: false

  install:
    spec:
      deployments:
      - name: codeready-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: codeready-operator
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                name: codeready-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: codeready-operator
                image: docker.io/schtool/codeready-operator:0.1
                imagePullPolicy: Always
                name: codeready-operator
                resources: {}
              serviceAccountName: codeready-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - routes
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          - routes
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - deploymentconfigs
          - routes
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - codeready.redhat.com
          resources:
          - '*'
          - routes
          - codereadys
          verbs:
          - '*'
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          - routes
          verbs:
          - '*'
        - apiGroups:
          - metrics.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - alertmanagers
          - alertmanagers/finalizers
          - prometheuses
          - prometheuses/finalizers
          - prometheusrules
          - servicemonitors
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - kube-state-metrics
          resources:
          - deployments
          verbs:
          - get
          - update
        - apiGroups:
          - extensions
          resourceNames:
          - kube-state-metrics
          resources:
          - deployments
          verbs:
          - get
          - update
        serviceAccountName: codeready-operator
    strategy: deployment
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.1.0
